# Build Options
#   change yes to no to disable

AUDIO_SUPPORTED = no
RGB_MATRIX_SUPPORTED = no
RGBLIGHT_SUPPORTED = no
BOOTMAGIC_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

# Encoder
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes

#Via
VIA_ENABLE = yes

#Debug
CONSOLE_ENABLE=yes